name: GStreamer Test

on:
  workflow_dispatch:

jobs:
  sound-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgstreamer1.0-0 gstreamer1.0-tools

      - name: sound-ci-setup
        uses: LABSN/sound-ci-helpers@v1

      - name: Check GStreamer
        run: |
          gst-launch-1.0 https://radio-stream.nhk.jp/hls/live/2023501/nhkradiruakr2/master.m3u8
