name: 'Test'
on:
  workflow_dispatch:
jobs:
  job:
    name: ubuntu-22.04 3.12 python
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install sounddevice
      - run: python -m sounddevice
      - run: |
          set -xeo pipefail
          python -m sounddevice | grep "[82] out"
        name: Check that there is some output device
      - run: sleep 10
      - run: |
          set -xeo pipefail
          python -m sounddevice | grep "[82] out"
        name: Check that there is some output device after sleep
