name: YT-DLP PIPE Test

on:
  workflow_dispatch:

jobs:
  sound-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1

      - name: sound-ci-setup
        uses: LABSN/sound-ci-helpers@v1

      - name: Record Test
        run: |
          yt-dlp -f bestaudio -o - https://radio-stream.nhk.jp/hls/live/2023501/nhkradiruakr2/master.m3u8 | ffmpeg -i pipe:0 -t 20 -c copy output.m4a
