name: ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  proton-vpn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up proton VPN
        run: |
          sudo dpkg -i binary/protonvpn-stable-release_1.0.4_all.deb
          sudo apt update

      - name: Check repo package
        run: echo "62a9d849835de8a5664cf95329458bf1966780b15cec420bf707b5f7278b9027  protonvpn-stable-release_1.0.4_all.deb" | sha256sum --check -
