name: ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  proton-vpn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Set up Proton VPN
        run: mkdir -p binary && wget -P binary https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb

      - name: Check repo package
        run: echo "62a9d849835de8a5664cf95329458bf1966780b15cec420bf707b5f7278b9027  binary/protonvpn-stable-release_1.0.4_all.deb" | sha256sum --check -

      - name: Install Proton VPN
        run: |
          sudo dpkg -i binary/protonvpn-stable-release_1.0.4_all.deb
          sudo apt update && sudo apt upgrade

      - name: Install tools
        run: |
          sudo apt install -y openvpn dialog expect
          python -m pip install --upgrade pip
          sudo pip install protonvpn-cli

      - name: ProtonVPN Login
        env: 
          PROTONVPN_OPENVPN_USERNAME: ${{ secrets.PROTONVPN_OPENVPN_USERNAME }}
          PROTONVPN_OPENVPN_PASSWORD: ${{ secrets.PROTONVPN_OPENVPN_PASSWORD }}
        run: |
          expect -c '
          set timeout 30
          spawn sudo protonvpn init
          expect {
            "Enter your ProtonVPN OpenVPN username:" {
              send "$PROTONVPN_OPENVPN_USERNAME\r"
            }
            timeout {
              puts "Failed at username prompt"
              exit 1
            }
          }
          expect {
            "Enter your ProtonVPN OpenVPN password:" {
              send "$PROTONVPN_OPENVPN_PASSWORD\r"
            }
            timeout {
              puts "Failed at password prompt"
              exit 1
            }
          }
          expect {
            "Confirm your ProtonVPN OpenVPN password:" {
              send "$PROTONVPN_OPENVPN_PASSWORD\r"
            }
            timeout {
            }
            eof
          }
          expect "Your plan:"
          send "1\r"
          expect "Your choice:"
          send "1\r"
          expect "Is this information correct? [Y/n]:"
          send "y\r"
          expect eof
          '

      - name: Disable IPv6
        run: sudo bash scripts/update-sysctl.sh

      - name: Connect to ProtonVPN
        run: sudo protonvpn c --cc JP

      - name: Check the country
        run: |
          IP=$(curl -s http://ifconfig.me)
          echo "IP Address: $IP"
          COUNTRY=$(curl -s https://ipinfo.io/${IP}/country)
          echo "Country Code: $COUNTRY"
