name: ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  proton-vpn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Proton VPN
        run: mkdir -p binary && wget -P binary https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb

      - name: Check repo package
        run: echo "62a9d849835de8a5664cf95329458bf1966780b15cec420bf707b5f7278b9027  binary/protonvpn-stable-release_1.0.4_all.deb" | sha256sum --check -

      - name: Install Proton VPN
        run: |
          sudo dpkg -i binary/protonvpn-stable-release_1.0.4_all.deb
          sudo apt update && sudo apt upgrade

      - name: Install tools
        run: |
          sudo apt install -y protonvpn-cli
          sudo apt install -y expect

      - name: ProtonVPN Login
        env: 
          PROTONVPN_USERNAME: ${{ secrets.PROTONVPN_USERNAME }}
          PROTONVPN_PASSWORD: ${{ secrets.PROTONVPN_PASSWORD }}
        run: |
          expect <<EOF
          set timeout 10
          spawn protonvpn-cli login $env(PROTONVPN_USERNAME)
          expect "Password:"
          send "$env(PROTONVPN_PASSWORD)\r"
          expect "$"
          EOF
