name: ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  proton-vpn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Set up Proton VPN
        run: mkdir -p binary && wget -P binary https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb

      - name: Check repo package
        run: echo "62a9d849835de8a5664cf95329458bf1966780b15cec420bf707b5f7278b9027  binary/protonvpn-stable-release_1.0.4_all.deb" | sha256sum --check -

      - name: Install Proton VPN
        run: |
          sudo dpkg -i binary/protonvpn-stable-release_1.0.4_all.deb
          sudo apt update && sudo apt upgrade

      - name: Install tools
        run: |
          sudo apt install -y openvpn dialog expect
          python -m pip install --upgrade pip
          sudo pip install protonvpn-cli
          pip install -U pytest-pretty

      - name: ProtonVPN Login
        env: 
          PROTONVPN_OPENVPN_USERNAME: ${{ secrets.PROTONVPN_OPENVPN_USERNAME }}
          PROTONVPN_OPENVPN_PASSWORD: ${{ secrets.PROTONVPN_OPENVPN_PASSWORD }}
          COLUMNS: 80
        run: |
          expect <<EOF
          set timeout 30
          spawn sudo protonvpn init
          expect "Enter your ProtonVPN OpenVPN username:"
          send "$env(PROTONVPN_OPENVPN_USERNAME)\r"
          echo "Pass username"
          expect "Enter your ProtonVPN OpenVPN password:"
          send "$env(PROTONVPN_OPENVPN_PASSWORD)\r"
          echo "Pass password"
          expect "Confirm your ProtonVPN OpenVPN password:"
          send "$env(PROTONVPN_OPENVPN_PASSWORD)\r"
          echo "Pass confirm"
          expect "Your plan:"
          send "1\r"
          echo "Pass check plan"
          expect "Your choice:"
          send "1\r"
          echo "Pass check choice"
          expect eof
          EOF

      - name: Disable IPv6
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

      - name: Connect to ProtonVPN
        run: sudo protonvpn c --cc JP

      - name: Check the country
        run: |
          IP=$(curl -s http://ifconfig.me)
          echo "IP Address: $IP"
          COUNTRY=$(curl -s https://ipinfo.io/${IP}/country)
          echo "Country Code: $COUNTRY"

      - name: Disconnect ProtonVPN
        run: sudo protonvpn disconnect
