name: ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  proton-vpn-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1

      - name: Set up Proton VPN
        run: mkdir -p binary && wget -P binary https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb

      - name: Check repo package
        run: echo "62a9d849835de8a5664cf95329458bf1966780b15cec420bf707b5f7278b9027  binary/protonvpn-stable-release_1.0.4_all.deb" | sha256sum --check -

      - name: Install Proton VPN
        run: |
          sudo dpkg -i binary/protonvpn-stable-release_1.0.4_all.deb
          sudo apt update && sudo apt upgrade

      - name: Install tools
        run: |
          sudo apt install -y openvpn dialog expect python3-pip python3-setuptools
          git clone https://github.com/ProtonVPN/linux-cli-community
          sudo pip3 install -e linux-cli-community
          pip3 install -U pytest-pretty

      - name: ProtonVPN Login
        env: 
          PROTONVPN_OPENVPN_USERNAME: ${{ secrets.PROTONVPN_OPENVPN_USERNAME }}
          PROTONVPN_OPENVPN_PASSWORD: ${{ secrets.PROTONVPN_OPENVPN_PASSWORD }}
        run: |
          faketty bash -c '
          stty cols 120 rows 40
          export COLUMNS=$(tput cols) LINES=$(tput lines)
          expect <<EOF
          set timeout 30
          spawn sudo protonvpn init
          expect "Enter your ProtonVPN OpenVPN username:"
          send "$env(PROTONVPN_OPENVPN_USERNAME)\r"
          puts "Pass username"
          expect "Enter your ProtonVPN OpenVPN password:"
          send "$env(PROTONVPN_OPENVPN_PASSWORD)\r"
          puts "Pass password"
          expect "Confirm your ProtonVPN OpenVPN password:"
          send "$env(PROTONVPN_OPENVPN_PASSWORD)\r"
          puts "Pass confirm"
          expect "Your plan:"
          send "1\r"
          puts "Pass check plan"
          expect "Your choice:"
          send "1\r"
          puts "Pass check choice"
          expect "Is this information correct? \\[Y/n\\]:"
          send "Y\r"
          puts "Pass check information"
          expect eof
          EOF
          '

      - name: Check ProtonVPN
        run: |
          protonvpn --version
          protonvpn status
          protonvpn --help

      - name: Disable IPv6
        run: |
          sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

      - name: Connect to ProtonVPN
        run: protonvpn c --cc JP

      - name: Check the country
        run: |
          IP=$(curl -s http://ifconfig.me)
          echo "IP Address: $IP"
          COUNTRY=$(curl -s https://ipinfo.io/${IP}/country)
          echo "Country Code: $COUNTRY"

      - name: Disconnect ProtonVPN
        run: sudo protonvpn disconnect
