name: Record Stream Test

on:
  workflow_dispatch:

jobs:
  sound-recording:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'

    - name: Set up ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt

    - name: sound-ci-setup
      uses: LABSN/sound-ci-helpers@v1

    - name: Run stream recording script
      run: |
        python scripts/radio_eikaiwa.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Record Test"
        title: "Record Radio from Streaming"
        body: "This is PR adds or updates"
        branch: record_streaming
        base: main
