name: Record Audio in dummy enironment test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev alsa-utils

      - name: Download kernel source
        run: |
          mkdir -p kernel
          cd kernel
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.6.tar.xz
          tar -xJf linux-6.10.6.tar.xz
          cd linux-6.10.6

      - name: Verify Makefile existence in root
        run: |
          cd kernel/linux-6.10.6
          if [ -f Makefile ]; then
            echo "Root Makefile found"
          else
            echo "Root Makefile not found, checking subdirectories"
            find . -name Makefile
          fi
          if [ -f Kconfig ]; then
            echo "Root Kconfig found"
          else
            echo "Root Kconfig not found, checking subdirectories"
            find . -name Kconfig
          fi
          if [ -f sound/drivers/dummy/Makefile ]; then
            echo "sound/drivers/Makefile found"
          else
            echo "sound/drivers/Makefile not found"
          fi
          
      - name: Copy custom config
        run: |
          cp .config kernel/linux-6.10.6/
          cd kernel/linux-6.10.6
          make olddefconfig
      # 事前に作成したconfigを使用して確認
      
      #- name: List directory structure
      #  run: |
      #    cd kernel/linux-6.10.6
      #    find . -type d -print > directory_structure.log
      #    find . -type f -print >> directory_structure.log
      #    cat directory_structure.log

      - name: Build snd-dummy module
        run: |
          cd kernel/linux-6.10.6
          make prepare
          make modules_prepare
          make M=sound/drivers
          sudo make M=sound/drivers modules_install
	  
      - name: List available sound devices
        run: |
          arecord -L
	  
      - name: Record audio
        run: |
          arecord -D dummy -f cd -t wav -d 10 -r 44100 Peak_test_A.wav
