name: Record Audio in dummy enironment test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev

      - name: Download kernel source
        run: |
          mkdir -p kernel
          cd kernel
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.6.tar.xz
          tar -xJf linux-6.10.6.tar.xz
          cd linux-6.10.6

      - name: Verify Makefile existence in root
        run: |
          cd kernel/linux-6.10.6
          if [ -f Makefile ]; then
            echo "Root Makefile found"
          else
            echo "Root Makefile not found, checking subdirectories"
            find . -name Makefile
          fi
        
      - name: List directory structure
        run: |
          cd kernel
          cd linux-6.10.6
          find . -type d -print > directory_structure.log
          find . -type f -print >> directory_structure.log
          cat directory_structure.log

      - name: Build snd-dummy module
        run: |
          make menuconfig
          make prepare
          make modules_prepare
          cd sound/core
          make M=sound/drivers/dummy
          sudo make M=sound/drivers/dummy modules_install

      - name: Load snd-dummy module
        run: |
          sudo modprobe snd-dummy

      - name: Record audio
        run: |
          arecord -D dummy -f cd -t wav -d 10 -r 44100 Peak_test_A.wav
