name: Script Test
on:
  workflow_dispatch:
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: sound-ci-setup
        uses: LABSN/sound-ci-helpers@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests npyscreen ffmpeg-python

      - name: Run script
        run: python scripts/radio-gogaku-downloader.py -q1 -p1 -d sample
