name: Sound CI helper

on:
  workflow_dispatch:

jobs:
  sound-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: sound-ci-helper
        uses: LABSN/sound-ci-helpers@v1
          
