name: Sound CI Test

on:
  workflow_dispatch:

jobs:
  sound-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo apt-get install portaudio19-dev

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: sound-ci-setup
        uses: LABSN/sound-ci-helpers@v1

      - name: List audio devices
        run: |
          python -c "import sounddevice as sd; print(sd.query_devices())"

      - name: Test audio output
        run: |
          python -c "import sounddevice as sd; print('Output devices:', [d for d in sd.query_devices() if d['max_output_channels'] > 0])"

      - name: Test audio input
        run: |
          python -c "import sounddevice as sd; print('Input devices:', [d for d in sd.query_devices() if d['max_input_channels'] > 0])"

      - name: Print PulseAudio Info
        run: |
          pactl list sinks
          pactl list sources

      - name: Check PyAudio Device
        run: |
          python scripts/sounddevice_check.py

      - name: List files
        run: ls -l
          
