name: SSL Test
on:
  workflow_dispatch:
jobs:
  SSL_sh_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set execute permissions for the build script
      run: chmod +x scripts/setup_ffmpeg.sh

    - name: Build ffmpeg
      run: ./scripts/setup_ffmpeg.sh

    - name: Check ffmpeg
      run: ffmpeg -version

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-build-logs
        path: $HOME/scripts/ffmpeg_build_*.log
