name: Record Audio in dummy environment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  record:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev

      - name: Download kernel source
        run: |
          mkdir -p kernel
          cd kernel
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.6.tar.xz
          tar -xJf linux-6.10.6.tar.xz
          cd linux
          git checkout $(uname -r)
      # Check out the kernel version matching the runner

      - name: Prepare kernel source
        run: |
          cd linux
          make oldconfig
          make prepare
          make modules_prepare

      - name: Build snd-dummy module
        run: |
          cd linux
          make M=sound/core

      - name: Install snd-dummy module
        run: |
          sudo cp linux/sound/core/snd-dummy.ko /lib/modules/$(uname -r)/kernel/sound/core/
          sudo depmod -a
          sudo modprobe snd-dummy

      - name: Verify dummy sound card
        run: |
          aplay -L


      #- name: Set up Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.x'
        
      #- name: Set up the dummy sound card
      #  run: |
      #    sudo modprobe snd-dummy
      #    echo "pcm.!default { type hw card 0 }" | sudo tee /etc/asound.conf
      #    echo "ctl.!default { type hw card 0 }" | sudo tee -a /etc/asound.conf
          
      - name: Install necessary packages
        run: |
          sudo apt-get install -y alsa-utils

      #- name: Install dependence
      #  run: |
      #    sudo apt-get install -y portaudio19-dev
      #    python -m pip install 

      - name: Record audio
        run: |
          # 録音するファイル名を指定してください
          arecord -D hw:0,0 -f cd -t wav -d 10 Peak_test_A.wav
          
      #- name: Pull Requests
      #  uses: peter-evans/create-pull-requests@v6
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    commit-message: "This is dummy environment record test"
      #    title: "Record test"
      #    body: "this is PR adds"
      #    branch: record_dummy
      #    base: main
