name: Record Audio

# 手動実行をトリガーとする
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  record_audio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update apt-get
        run: |
          sudo apt-get update

      - name: Set up virtual audio device
        run: |
          sudo apt-get install -y alsa-utils alsa-oss sox
          sudo modprobe snd-aloop
          cat /proc/asound/cards
          cat /proc/asound/devices
        #  sudo modprobe snd-dummy
        #  cat /proc/asound/cards
        #  cat /proc/asound/devices
        #  pacmd load-module module-null-sink sink_name=VirtualSink
        #  pacmd set-default-sink VirtualSink

      - name: Install portaudio dependencies
        run: |
          sudo apt-get install -y portaudio19-dev

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install -r scripts/requirement.txt

      - name: Record audio
        run: |
          . venv/bin/activate
          python scripts/test.py

      - name: Pull Requests
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Record Test"
          title: "Record Radio from Streaming"
          body: "This is PR adds or updates"
          branch: record_streaming
          base: main
