name: Record Audio

# 手動実行をトリガーとする
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  record_audio:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install get-chrome-driver --upgrade
          pip install -r scripts/requirement.txt

      - name: Record audio
        run: |
          python scripts/test.py

      - name: Pull Requests
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Record Test"
          title: "Record Radio from Streaming"
          body: "This is PR adds or updates"
          branch: record_streaming
          base: main
