name: Test
on:
  workflow_dispatch:
jobs:
  Output-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: sound-ci-setup
      uses: LABSN/sound-ci-helpers@v1

    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
    - run: pip install sounddevice
    - run: python -m sounddevice
    - run: |
        set -xeo pipefail
        python -m sounddevice | grep "[82] out"
      name: Check that there is some output device
    - run: sleep 10
    - run: |
        set -xeo pipefail
        python -m sounddevice | grep "[82] out"
      name: Check that there is some output device after sleep

    - name: Record the stream for 2 minutes
      run: |
        ffmpeg -i "https://www.nhk.or.jp/radio/player/?ch=r2" -t 120 -acodec copy output.wav
