name: Transcribe MP3 Files

on:
#  schedule:
#    - cron: '0 6 * * 1-5'  # UTCで平日の午前6時（JSTで午後5時)
  workflow_dispatch:    # 手動トリガーを有効にする設定

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Generate matrix dynamically
        id: set-matrix
        run: |
          # Pythonスクリプトを実行し、MP3とSRTのパスを検索
          python3 << EOF
            import os
            import json

            directory = '/content'  # ここに検索するディレクトリを指定

            srt_path = []

            # ディレクトリ内のファイルを再帰的に探索
            for root, dirs, files in os.walk(directory):
                for file in files:
                    if file.endswith('.mp3'):
                        file_without_ext = os.path.splitext(file)[0]
                        srt_file = os.path.join(root, file_without_ext + '.srt')
                        if not os.path.exists(srt_file):
                            srt_path.append(srt_file)

            matrix = srt_path

            # GITHUB_ENVに結果を出力
            print(f"::set-output name=matrix::{matrix_json}")
          EOF

  example_job:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
    steps:
      - name: Print combination
        run: echo "Audio: ${{ matrix.audio }} need SRT (missing): ${{ matrix.srt }}"
