name: Transcribe MP3 Files

on:
  schedule:
    - cron: '0 6 * * 1-5'  # UTCで平日の午前6時（JSTで午後5時)
  workflow_dispatch:    # 手動トリガーを有効にする設定

jobs:
  find_mp3_files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.find_mp3_files.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Find MP3 files without transcript
        id: find_mp3_files
        run: |
          mp3_files=$(find . -type f -name "*.mp3")
          files_to_process=()
          for file in $mp3_files; do
            srt_file="${file%.mp3}.srt"
            if [ ! -f "$srt_file" ]; then
              files_to_process+=("$file")
            fi
          done
          files_output=$(printf "%s\n" "${files_to_process[@]}" | jq -R . | jq -s .)
          echo "::set-output name=files::$files_output"

  transcribe_files:
    needs: find_mp3_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.find_mp3_files.outputs.files) }}
    steps:
      - name: Transcribe files
        if: matrix.file != ''
        uses: appleboy/whisper-action@v0.1.1
        with:
          model: small
          audio_path: ${{ matrix.file }}
          output_format: srt
          output_folder: transcripts
          print_progress: true
          translate: false

      - name: Save transcript as .src
        if: matrix.file != ''
        run: |
          for file in ${{ matrix.file }}; do
            transcript_file="transcripts/${file%.mp3}.srt"
            if [ -f "$transcript_file" ]; then
              mv "$transcript_file" "${file%.mp3}.srt"
            fi
          done
          ls
