name: WireGuard ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  wg-proton-vpn-test:
    runs-on: ubuntu-latest
    
    env:
      WG_CONF: ${{ secrets.WG_VPN_CONF }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

      - name: Create WireGuard config file
        run: |
          echo "$WG_CONF" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo ln -s /usr/bin/resolvectl /usr/local/bin/resolvconf
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Start WireGuard VPN
        run: |
          sudo wg-quick up wg0
          sleep 20

      - name: Verify VPN Connection
        run: |
          sudo wg | grep -v 'public key' | grep -v 'private key'
          sleep 10

      - name: Check external IP and country
        run: |
          IP=$(curl -s http://ifconfig.me)
          if [ -z "$IP" ]; then
            echo "Failed to retrieve external IP address."
            exit 1
          fi
          echo "IP Address: $IP"
          
          COUNTRY=$(curl -s https://ipinfo.io/${IP}/country)
          if [ -z "$COUNTRY" ]; then
            echo "Failed to retrieve country code."
            exit 1
          fi
          echo "Country Code: $COUNTRY"

      - name: End WireGuard VPN
        run: sudo wg-quick down wg0
