name: WireGuard ProtonVPN Test

on:
  workflow_dispatch:

jobs:
  wg-proton-vpn-test:
    runs-on: ubuntu-latest
    
    env:
      WG_CONF: ${{ secrets.WG_VPN_CONF }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
